name: Publish

on:
  release:
    types: [published]
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: node test/index.js

  check-version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check Version
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: ./package.json
      - name: If Version Changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "version change"'
      - name: If Not Version Changed
        if: steps.check.outputs.changed != 'true'
        run: 'echo "No version change"'
